default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: expenses_tracker_db

production:
  <<: *default
  database: expenses_tracker_db
  url: <%= ENV['DATABASE_URL'] %>